### PR TITLE
apps: add Podigee Podcast Hosting and Analytics

### PR DESCRIPTION
**Pull request by spiderpug**
Hey there,

I would like to propose the addition of "Podigee - Podcast Hosting and Analytics" to the list of Apps.

### CODE REVIEW

**Comment by daveajones** [comment]
Thanks!!

**Comment by spiderpug** [comment]
Thank you as well! 

Will this change also trigger an update of https://podcasting2.org/publishing-tools and list us there?

**Comment by daveajones** [comment]
I believe so, but we don't control that site.  That's @theDanielJLewis .  Daniel?

**Comment by theDanielJLewis** [comment]
Yes, we're still using Podcast Index's data for our publishing tools and podcast apps. So if you update PI's data, it will show up on Podcasting2.org's site on our next rebuild.

**Comment by spiderpug** [comment]
Awesome! Looking forward to a rebuild 👍

**Pull request merged**
