### PR TITLE
Added podcastpage.io to apps.json

### PR DESCRIPTION
**Pull request by stpp2**
( Couldn't upload the logo. Asset can be added from here - https://www.dropbox.com/s/7q59zgsfxzf46zi/podcastpage.png?dl=1 )

### CODE REVIEW

**Comment by daveajones** [comment]
I’ll fix it.

**Comment by stpp2** [comment]
@daveajones - pushed a fix for potential merge conflicts since there was a new commit to the main branch since this PR.
Would really appreciate it if you could merge to avoid additional conflicts 😀

**Comment by daveajones** [comment]
Sorry. Forgot about this one.

**Comment by stpp2** [comment]
No worries! Thanks for the prompt merge, I really appreciate it.

**Comment by daveajones** [comment]
Image fixed now:  https://podcastindex.org/apps

**Pull request merged**
