### PR TITLE
Expand search to search music, title, person and other changes

### LINKED ISSUE #76: Add anchor target for individual episodes
Would be great if we could send out links to share specific episodes with each other.
Right now I can only link people to shows.

image

Is there an episode detail page I'm missing?

### PR DESCRIPTION
**Pull request by stevencrader**
Move episode list and player to separate component so it can be used on the podcast page and person search results.

Attempt to sort music feeds based on the season and episode attributes.
Sort live feeds by start time (newest first)

The proposed way to link to an episode is in the format `/podcast/<feed_id>?episode=<episode_id>`.  Ex: `/podcast/150842?episode=15569509454`
If a different URL scheme would be preferred, let me know. 

This was added to support the person search but will resolve #76 and #63 too.

Other changes:

- Stop fetching v4v feeds if page navigated away
- Fix mobile menu button staying highlighted on close
- Fix arrows in Recent widget being hard to tap on mobile
- If podcast page loaded with guid, redirect to page based on feed id (ex: `/podcast/e0ac9365-689c-5043-8804-15b9dfcc545a` will replace url with `/podcast/150842`). This preserves the episode argument.
- Add link to v4v stats on v4v page

### CODE REVIEW

**Comment by stevencrader** [comment]
Set to draft while I add a commit to handle URL in search dialog. Title and person show "add" message when the feed actually already exists in the index.

**Comment by stevencrader** [comment]
# Screenshots

New search field in topbar
image

All resutls
image

Music resutls
image

Title results
image

Person results, no results
image

Person results with matching episodes and player on results page.
image

Click chain icon to link to episode on PodcastIndex.org. When loading page with episode, will scroll to episode.
image

Episode name in player will also link to episode page
image

**Comment by daveajones** [comment]
This looks really good Steven. I’m not qualified to reviews the code but I will if someone else more Reacty doesn’t step in. The screenshots look great. 💪

**Comment by daveajones** [comment]
Exposing person search and links to episodes is a long needed thing.

**Comment by daveajones** [comment]
You good to go on this?

**Comment by stevencrader** [comment]
Yes.

**Pull request merged**
