### PR TITLE
Adds N2N2 application.

### PR DESCRIPTION
**Pull request by masterial**
Please add our application to your index. Thank you!

### CODE REVIEW

**Comment by stevencrader** [comment]
The URL https://n2n2.co/ doesn't return anything.  What does the app do?

**Comment by justinrezvani** [comment]
> The URL https://n2n2.co/ doesn't return anything. What does the app do?

I have spoken with Adam Curry, he knows who we are and knows about our app, we are launching a decentralized community membership network that allows creators and audiences to monetize efficiently and privately using the lighting network. 

Here is the staging site --> http://staging.n2n2.co/

**Comment by stevencrader** [comment]
That's cool. I look forward to it launching.

**Comment by justinrezvani** [comment]
> That's cool. I look forward to it launching.

great, can the code commit be approved for our integration?

**Comment by stevencrader** [comment]
> great, can the code commit be approved for our integration? 

I would say yes but I don't have permission to do that. We need @daveajones

**Comment by daveajones** [comment]
Sure. I’ll check it and merge in the morning.

**Pull request merged**
