### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by nathangathright**
- Remove AudioWave
- Remove Sounder
- Remove Podtrics
- Add Live to Podcast Addict
- Add Social Interact to Podverse
- Add Social Interact to Podfriend

### CODE REVIEW

**Comment by nathangathright** [comment]
@mitchdowney @MartinMouritzen @johnspurlock-skymethod @daveajones Any other little tweaks I should roll into this PR?

**Comment by daveajones** [comment]
Oh, thanks for this Nathan.  If you can add TXT to RSS.com that'd be good.  It's on my to-do list.

**Comment by nathangathright** [comment]
@daveajones looks like that’s already live https://podcastindex.org/apps?appTypes=hosting&elements=Txt

**Comment by mitchdowney** [comment]
Thanks @nathangathright! It looks good. I noticed this tiny bug on the site https://github.com/Podcastindex-org/web-ui/pull/235/files#diff-d98390923cdcbc9667b2674389f6303e9369f42ff06f9b424cfe9bb9364d315bR2141

**Comment by nathangathright** [comment]
Thanks @mitchdowney. I took care of that in 4f6f53b, but forgot to update from 'upstream/master' before starting this branch.

**Comment by dellagustin** [comment]
Fixes https://github.com/Podcastindex-org/web-ui/issues/217

**Pull request merged**
